import {COLORS} from '../enums'


export const typography ={
  default:{
    fontSize:40,
    fontWeight:"500",
  },
  title01:{
    fontSize:40,
    fontWeight:"500",
  },
  title02:{
    fontSize:36,
    fontWeight:"700",
  },
  title03:{
    fontSize:32,
    fontWeight:"700",
  },
  title04:{
    fontSize:28,
    fontWeight:"700",
  },
  title05:{
    fontSize:24,
    fontWeight:"700",
  },
  subtitle01:{
    fontSize:20,
    fontWeight:"500",
  },
  subtitle02:{
    fontSize:16,
    fontWeight:"500",
  },
  subtitle03:{
    fontSize:14,
    fontWeight:"500",
  },
  subtitle04:{
    fontSize:12,
    fontWeight:"500",
  },
  content00:{
    fontSize:24,
    fontWeight:"300",
  },
  content01:{
    fontSize:20,
    fontWeight:"300",
  },
  content02:{
    fontSize:16,
    fontWeight:"300",
  },
  content03:{
    fontSize:14,
    fontWeight:"300",
  },
  content04:{
    fontSize:13,
    fontWeight:"400",
  },
  textxs:{
    fontSize:10,
    fontWeight:"500",
  },
  text00:{
    fontSize:12,
    fontWeight:"500",
  },
  text01:{
    fontSize:14,
    fontWeight:"500",
  },
  text02:{
    fontSize:16,
    fontWeight:"500",
  },
  text03:{
    fontSize:18,
    fontWeight:"500",
  },
  text04:{
    fontSize:20,
    fontWeight:"500",
  },
  head01:{
    fontSize:24,
    fontWeight:"400",
  },
  color:{

    primary:COLORS.PRIMARY_BLUE,
    text:COLORS.TEXT,
    lightText:COLORS.LIGHT_TEXT,
    grayText:COLORS.GRAY_TEXT,
    secondary:COLORS.SECONDARY,
    dark:COLORS.PRIMARY_DARK_BLUE,
    black:COLORS.BLACK,
    white:COLORS.WHITE,
    gray:COLORS.HINT_GRAY,
    lightgray:COLORS.GRAY,
    error:COLORS.ERROR,
  }

};
