const PAGES =  {
    LOGIN: 'Login',
    ACCOUNT_LIST:'AccountList',
    BRAND_SELECT:"BrandSelect",
    DEVICE_MANAGE:"DeviceManage",
    DEVICE_ADD:"DeviceAdd",
    DEVICE_ADD2:"DeviceAdd2",
    DEVICE_ADD_LIST:"DeviceAddList",
    DEVICE_SCAN:"DeviceScan",
    EVENT_MANAGE:"EventManage",
    DATA_ANALYSIS:"DataAnalysis",
    DATA_DETAIL:"DataDetail",
    DATA_MONITOR:"DataMonitor",
    SETTING_ADDRESS:"SettingAddress",
    SETTING_PASSWORD:"SettingPassword",
    SETTING_LANG:"SettingLang",
    NOTIFICATION:"Notification",
    FILTER_DATE:"FilterDate",
    FILTER_DATE_RANGE:"FilterDateRange",
    FILTER_MAIN:"FilterMain",
    FILTER_REGION1:"FilterRegion1",
    FILTER_REGION2:"FilterRegion2",
    FILTER_SORT:"FilterSort",
    FILTER_STORE:"FilterStore",
    EVENT_HISTORY:"EventHistory",
    EVENT_DETAIL:"EventDetail",
    EVENT_RELATED:"EventRelated",
    EVENT_INSPECT:"EventInspect",
    MORE:"More",

}

export default PAGES;
