export const COLORS = {
  WHITE:"#fff",
  BLACK:"#000",
  TEXT:"#2B2B2B",
  LIGHT_TEXT:"#A5A5A5",
  GRAY_TEXT:"#919191",
  BG:"#F0F0F0",
  FOCUS_BG:"#E2EFFD",
  DISABLE_BG:"#CECECE",
  DISABLE_GRAY:"#E2EFFD",
  PRIMARY_BLUE:"#006AB7",
  PRIMARY_DARK_BLUE:"#003B65",
  GRAY:"#E3E3E3",
  HINT_GRAY:"#7D7D7D",
  ERROR:"#CA4940",
  SECONDARY:"#35CDA8",
};

export const ICONS = {
  "toast-successful":require("../assets/icons/toast/successful.png"),
  "toast-information":require("../assets/icons/toast/information.png"),
  "toast-warning":require("../assets/icons/toast/warning.png"),
  "toast-error":require("../assets/icons/toast/error.png"),
  "scan-normal":require("../assets/icons/scan/normal.png"),
  "scan-active":require("../assets/icons/scan/active.png"),
  "scan-disable":require("../assets/icons/scan/normal.png"),
  "view-detail-normal":require("../assets/icons/view-detail/normal.png"),
  "view-detail-active":require("../assets/icons/view-detail/normal.png"),
  "view-detail-disable":require("../assets/icons/view-detail/normal.png"),
  "add-new-normal":require("../assets/icons/add-new/normal.png"),
  "add-new-active":require("../assets/icons/add-new/normal.png"),
  "add-new-disable":require("../assets/icons/add-new/normal.png"),
  "cancel-normal":require("../assets/icons/cancel/normal.png"),
  "cancel-active":require("../assets/icons/cancel/normal.png"),
  "cancel-disable":require("../assets/icons/cancel/normal.png"),
  "info-normal":require("../assets/icons/action/info/normal.png"),
  "info-active":require("../assets/icons/action/info/active.png"),
  "info-disable":require("../assets/icons/action/info/disable.png"),
  "back-normal":require("../assets/icons/back/normal.png"),
  "back-active" :require("../assets/icons/back/active.png"),
  "back-disable" :require("../assets/icons/back/disable.png"),
  "next-normal":require("../assets/icons/next/normal.png"),
  "next-active" :require("../assets/icons/next/active.png"),
  "next-disable" :require("../assets/icons/next/disable.png"),
  "successful" :require("../assets/icons/successful.png"),
  "password-hide" :require("../assets/icons/text-fields/password/hide/active.png"),
  "password-show" :require("../assets/icons/text-fields/password/show/active.png"),
  "Custom_iQM_ColdChain-normal":require("../assets/icons/coldchain/normal.png"),
  "Custom_iQM_ColdChain-active":require("../assets/icons/coldchain/selected.png"),
  "header-back-normal":require("../assets/icons/header/back/normal.png"),
  "header-back-active" :require("../assets/icons/header/back/active.png"),
  "header-back-disable" :require("../assets/icons/header/back/disable.png"),
  "header-event-normal":require("../assets/icons/header/event/normal.png"),
  "header-event-active" :require("../assets/icons/header/event/active.png"),
  "header-event-disable" :require("../assets/icons/header/event/disable.png"),
  "header-event-alert-normal":require("../assets/icons/header/event-alert/normal.png"),
  "header-event-alert-active" :require("../assets/icons/header/event-alert/active.png"),
  "header-event-alert-disable" :require("../assets/icons/header/event-alert/disable.png"),
  "list-enter-normal":require("../assets/icons/list/enter/normal.png"),
  "list-enter-active" :require("../assets/icons/list/enter/active.png"),
  "list-enter-disable" :require("../assets/icons/list/enter/disable.png"),
  "list-clear-normal":require("../assets/icons/list/clear/normal.png"),
  "list-clear-active" :require("../assets/icons/list/clear/active.png"),
  "list-select-normal":require("../assets/icons/list/select/normal.png"),
  "list-select-active" :require("../assets/icons/list/select/active.png"),
  "nav-device-mgt-normal":require("../assets/icons/device-mgt/normal.png"),
  "nav-device-mgt-active":require("../assets/icons/device-mgt/active.png"),
  "nav-device-mgt-disable":require("../assets/icons/device-mgt/disable.png"),
  "nav-event-mgt-normal":require("../assets/icons/event-mgt/normal.png"),
  "nav-event-mgt-active":require("../assets/icons/event-mgt/active.png"),
  "nav-event-mgt-disable":require("../assets/icons/event-mgt/disable.png"),
  "nav-data-analysis-normal":require("../assets/icons/data-analysis/normal.png"),
  "nav-data-analysis-active":require("../assets/icons/data-analysis/active.png"),
  "nav-data-analysis-disable":require("../assets/icons/data-analysis/disable.png"),
  "nav-more-normal":require("../assets/icons/more/normal.png"),
  "nav-more-active":require("../assets/icons/more/active.png"),
  "nav-more-disable":require("../assets/icons/more/disable.png"),
  "checkbox-selected-normal":require("../assets/icons/checkbox/selected/normal.png"),
  "checkbox-selected-disable":require("../assets/icons/checkbox/selected/disable.png"),
  "checkbox-sub-selected-normal":require("../assets/icons/checkbox/sub-selected/normal.png"),
  "checkbox-sub-selected-disable":require("../assets/icons/checkbox/sub-selected/disable.png"),
  "checkbox-unselect-normal":require("../assets/icons/checkbox/unselect/normal.png"),
  "checkbox-unselect-disable":require("../assets/icons/checkbox/unselect/disable.png"),
  "list-group-collapse-normal":require("../assets/icons/list/group/collapse/normal.png"),
  "list-group-collapse-active":require("../assets/icons/list/group/collapse/active.png"),
  "list-group-expand-normal":require("../assets/icons/list/group/expand/normal.png"),
  "list-group-expand-active":require("../assets/icons/list/group/expand/active.png"),
  "text-fields-search-normal":require("../assets/icons/text-fields/search/normal.png"),
  "text-fields-search-active":require("../assets/icons/text-fields/search/active.png"),
  "text-fields-search-disable":require("../assets/icons/text-fields/search/disable.png"),
  "text-fields-date-normal":require("../assets/icons/text-fields/date/normal.png"),
  "text-fields-date-active":require("../assets/icons/text-fields/date/active.png"),
  "text-fields-date-disable":require("../assets/icons/text-fields/search/disable.png"),
  "filter-normal":require("../assets/icons/filter/normal.png"),
  "filter-active":require("../assets/icons/filter/active.png"),
  "filter-disable":require("../assets/icons/filter/disable.png"),
  "filter-active-normal":require("../assets/icons/filter-active/normal.png"),
  "filter-active-active":require("../assets/icons/filter-active/active.png"),
  "filter-active-disable":require("../assets/icons/filter-active/disable.png"),
  "illustration-process-status-done":require("../assets/icons/illustration/process-status/done.png"),
  "illustration-process-status-pending":require("../assets/icons/illustration/process-status/pending.png"),
  "illustration-module-status-outline-error":require("../assets/icons/illustration/module-status-outline/error.png"),
  "illustration-module-status-outline-normal":require("../assets/icons/illustration/module-status-outline/normal.png"),
  "illustration-module-status-outline-pause":require("../assets/icons/illustration/module-status-outline/pause.png"),
  "illustration-module-status-outline-stop":require("../assets/icons/illustration/module-status-outline/stop.png"),
  "illustration-module-status-filled-error":require("../assets/icons/illustration/module-status-filled/error.png"),
  "illustration-module-status-filled-normal":require("../assets/icons/illustration/module-status-filled/normal.png"),
  "illustration-module-status-filled-pause":require("../assets/icons/illustration/module-status-filled/pause.png"),
  "illustration-module-status-filled-stop":require("../assets/icons/illustration/module-status-filled/stop.png"),
  "illustration-module-status-filled-defrost":require("../assets/icons/illustration/module-status-filled/defrost.png"),
  "illustration-module-status-error":require("../assets/icons/illustration/module-status/error.png"),
  "illustration-module-status-normal":require("../assets/icons/illustration/module-status/normal.png"),
  "illustration-module-status-pause":require("../assets/icons/illustration/module-status/pause.png"),
  "illustration-module-status-stop":require("../assets/icons/illustration/module-status/stop.png"),
  "illustration-module-status-defrost":require("../assets/icons/illustration/module-status/defrost.png"),
  "illustration-dashboard-legend-error":require("../assets/icons/illustration/dashboard-legend/error.png"),
  "illustration-dashboard-legend-smart":require("../assets/icons/illustration/dashboard-legend/smart.png"),
  "illustration-dashboard-legend-normal":require("../assets/icons/illustration/dashboard-legend/normal.png"),
  "illustration-dashboard-legend-pause":require("../assets/icons/illustration/dashboard-legend/pause.png"),
  "illustration-dashboard-legend-stop":require("../assets/icons/illustration/dashboard-legend/stop.png"),
  "illustration-in-card-activation-control-activate":require("../assets/icons/illustration/in-card/activation-control/activate.png"),
  "illustration-in-card-activation-control-delete":require("../assets/icons/illustration/in-card/activation-control/delete.png"),
  "illustration-in-card-activation-control-pause":require("../assets/icons/illustration/in-card/activation-control/pause.png"),
  "illustration-in-card-activation-control-stop":require("../assets/icons/illustration/in-card/activation-control/stop.png"),
  "illustration-device-status-delete":require("../assets/icons/illustration/device-status/delete.png"),
  "illustration-device-status-normal":require("../assets/icons/illustration/device-status/normal.png"),
  "illustration-device-status-expired":require("../assets/icons/illustration/device-status/expired.png"),
  "illustration-device-status-rest":require("../assets/icons/illustration/device-status/rest.png"),
  "illustration-device-status-termination":require("../assets/icons/illustration/device-status/termination.png"),
  "illustration-device-status-unactivated":require("../assets/icons/illustration/device-status/unactivated.png"),
  "illustration-device-status-no-data":require("../assets/icons/illustration/device-status/no-data.png"),
  "illustration-device-status-offline":require("../assets/icons/illustration/device-status/offline.png"),
  "illustration-device-status-unbind":require("../assets/icons/illustration/device-status/unbind.png"),
  "illustration-in-card-signal-bad":require("../assets/icons/illustration/in-card/signal/bad.png"),
  "illustration-in-card-signal-good":require("../assets/icons/illustration/in-card/signal/good.png"),
  "illustration-in-card-signal-none":require("../assets/icons/illustration/in-card/signal/none.png"),
  "illustration-in-card-signal-normal":require("../assets/icons/illustration/in-card/signal/normal.png"),
  "illustration-in-card-battery-bad":require("../assets/icons/illustration/in-card/battery/low.png"),
  "illustration-in-card-battery-good":require("../assets/icons/illustration/in-card/battery/good.png"),
  "illustration-in-card-battery-none":require("../assets/icons/illustration/in-card/battery/none.png"),
  "illustration-in-card-battery-normal":require("../assets/icons/illustration/in-card/battery/normal.png"),
  "illustration-event-checked":require("../assets/icons/illustration/event-status/checked.png"),
  "illustration-event-unchecked":require("../assets/icons/illustration/event-status/unchecked.png"),
  "illustration-event-alarm":require("../assets/icons/illustration/event-status/alarm.png"),
  "in-filled-button-add-new":require("../assets/icons/in-filled-button/add-new/normal.png"),
  "in-filled-button-scroll-to-top":require("../assets/icons/in-filled-button/scroll-to-top.png"),
  "illustration-unit-status-delete":require("../assets/icons/illustration/unit-status/delete.png"),
  "illustration-unit-status-stop-running":require("../assets/icons/illustration/unit-status/stoprunning.png"),
  "illustration-unit-status-normal":require("../assets/icons/illustration/unit-status/normal.png"),
  "illustration-unit-status-defrost":require("../assets/icons/illustration/unit-status/defrost.png"),
  "illustration-unit-status-error":require("../assets/icons/illustration/unit-status/error.png"),
  "illustration-unit-status-pause":require("../assets/icons/illustration/unit-status/pause.png"),
  "illustration-unit-status-stop":require("../assets/icons/illustration/unit-status/stop.png"),
  "illustration-unit-status-no-data":require("../assets/icons/illustration/unit-status/no-data.png"),
  "illustration-unit-status-offline":require("../assets/icons/illustration/unit-status/offline.png"),
  "illustration-unit-status-unbind":require("../assets/icons/illustration/unit-status/unbind.png"),
  "illustration-no-data":require("../assets/icons/illustration/no-data.png"),
  "action-info":require("../assets/icons/action/info/normal.png"),
  "action-search":require("../assets/icons/action/search/normal.png"),
  "search-item":require("../assets/icons/action/search/search.png"),
  "action-sort":require("../assets/icons/action/sort/normal.png"),
  "header-filter-normal":require("../assets/icons/header/filter/normal.png"),
  "header-filter-active":require("../assets/icons/header/filter/normal.png"),
  "header-filter-disable":require("../assets/icons/header/filter/normal.png"),
  "header-filteractive-normal":require("../assets/icons/header/filter/active.png"),
  "header-filteractive-active":require("../assets/icons/header/filter/active.png"),
  "header-filteractive-disable":require("../assets/icons/header/filter/active.png"),
  "dropdown-normal":require("../assets/icons/dropdown/normal.png"),
  "dropdown-active":require("../assets/icons/dropdown/active.png"),
  "dropdown-blue":require("../assets/icons/dropdown/blue.png"),
  "dropdown-blue-active":require("../assets/icons/dropdown/blueactive.png"),
  "more":require("../assets/icons/action/more/normal.png"),
  "calendar":require("../assets/icons/action/calendar/normal.png"),
  "illustration-station-status-normal":require("../assets/icons/illustration/station-status/normal.png"),
  "illustration-station-status-error":require("../assets/icons/illustration/station-status/error.png"),
  "illustration-station-status-stop":require("../assets/icons/illustration/station-status/stop.png"),
  "illustration-station-status-pause":require("../assets/icons/illustration/station-status/pause.png"),
  "illustration-station-status-defrost":require("../assets/icons/illustration/station-status/defrost.png"),
  "illustration-station-status-delete":require("../assets/icons/illustration/station-status/delete.png"),
  "illustration-dot-status-normal":require("../assets/icons/illustration/status-dot/normal.png"),
  "illustration-dot-status-stop":require("../assets/icons/illustration/status-dot/stop.png"),
  "illustration-dot-status-pause":require("../assets/icons/illustration/status-dot/pause.png"),
  "illustration-dot-status-delete":require("../assets/icons/illustration/status-dot/delete.png"),
  "monitor_type_humidity":require("../assets/icons/monitor-type/humidity.png"),
  "monitor_type_temperature":require("../assets/icons/monitor-type/temperature.png"),
  "monitor_type_switch":require("../assets/icons/monitor-type/switch.png"),
  "clear":require("../assets/icons/action/clear/normal.png"),
  "send":require("../assets/icons/action/send/normal.png"),
  "edit":require("../assets/icons/action/edit/normal.png"),
  "back":require("../assets/icons/action/back/normal.png"),
  "edit-white":require("../assets/icons/action/edit/white.png"),
    "edit-white-normal":require("../assets/icons/action/edit/nedit.png"),
      "edit-white-active":require("../assets/icons/action/edit/nedit.png"),
        "edit-white-disable":require("../assets/icons/action/edit/nedit.png"),
  "select":require("../assets/icons/action/select/normal.png"),
  "add-new":require("../assets/icons/action/add-new/normal.png"),
  "delete":require("../assets/icons/action/delete/normal.png"),
  "delete-gray":require("../assets/icons/action/delete/gray.png"),
  "cancel":require("../assets/icons/action/cancel/normal.png"),
  "tips":require("../assets/icons/action/tips/unselected/normal.png"),
  "cancel-active":require("../assets/icons/action/cancel/normal.png"),
    "save":require("../assets/icons/action/save/normal.png"),
  "cancel-normal":require("../assets/icons/action/cancel/normal.png"),
  "delete-active":require("../assets/icons/action/delete/active.png"),
  "delete-disable":require("../assets/icons/action/delete/disable.png"),
      "mail":require("../assets/icons/mail.png"),

}
